PerviousClassesFolder
CodeSchool-Jr/website pull request #1
Opened 2020-06-25 20:33 UTC by Kumaravinash9

PerviousClass Folder

2020-06-25 20:49 UTC, subodhk01 requested changes
- Component is not responsive, that is very necessary.
- The component is not exactly how it was on the wireframe.

also you could have used https://flickity.metafizzy.co/ , its a really great library and can easily be made responsive and also try to make the changes on a different branch on the original repo.

2020-06-25 20:49 UTC, subodhk01 commented on RecorderdClasses/pre.html
> +<!DOCTYPE html>
should have used the index.html that was on the base directory

2020-06-26 01:25 UTC, Kumaravinash9 commented
Now,it's responsive .so have a look

2020-06-26 07:04 UTC, subodhk01 requested changes
Still not responsive
<img width="464" alt="Screenshot 2020-06-26 at 12 33 55" src="https://user-images.githubusercontent.com/19875783/85829957-5c0e0480-b7a9-11ea-8edf-bc92e84be371.png">

2020-06-26 07:05 UTC, subodhk01 commented
Try using https://flickity.metafizzy.co/ if you can

2020-06-26 20:03 UTC, subodhk01 commented
Merged to #3

2020-06-26 20:03 UTC, closed without merging